[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm run install:backend',
  'npm run install:frontend'
]

[phases.build]
cmds = ['npm run build:frontend']

[start]
cmd = 'npm start'
